services:
  backend:
    container_name: "zad10-backend"
    image: bkaj/backend-ebiz:latest
    ports:
      - "8000:8000"
    networks:
      - app-network
  frontend:
    container_name: "zad10-frontend"
    image: bkaj/frontend-ebiz:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      